from core.parameters import SIM_TIME, WEIGHTS, NUM_VEHICLES
import numpy as np
import time
import os
from strategies.deco_offloader import DECOOffloader
from strategies.game_theory import PotentialGameOffloader
from strategies.local_baseline import LocalOnlyOffloader
from strategies.random_baseline import RandomOffloader
from strategies.greedy_offloader import GreedyOffloader
from simulation.simulator import AutonomousVehicleSimulator
import random
import pandas as pd

# --- GLOBAL SEEDING (Set once at the very top for reproducible sequence across ALL runs) ---
GLOBAL_SEED = 42
random.seed(GLOBAL_SEED)
np.random.seed(GLOBAL_SEED)
# ------------------------------------------------------------------------------------------

LOG_DIR = "logs_iteration"
os.makedirs(LOG_DIR, exist_ok=True)


def run_single_comparison():
    """
    Runs a single comparison of strategies and returns a list of dictionaries,
    each representing a strategy's results for this run.
    The total_tasks_generated for the entire iteration is determined by the LocalOnly run.
    """
    strategies = {
        "Proposed": PotentialGameOffloader,
        "DECO": DECOOffloader,
        "Local": LocalOnlyOffloader,
        "Random": RandomOffloader,
        "Greedy": GreedyOffloader
    }

    run_log_data = []  # List to store data for this single run

    # --- Step 1: Establish baseline total_tasks_generated for THIS iteration ---
    print("\n=== Running LocalOnly Strategy to establish baseline total tasks generated for this iteration ===")
    local_sim = AutonomousVehicleSimulator(strategy=LocalOnlyOffloader)
    # The 'run' method will use the globally set random seed, ensuring consistency across iterations if tasks are generated by global RNG.
    local_metrics = local_sim.run(until=SIM_TIME)

    # This is the total number of tasks that were *generated* and either completed or failed
    # by the LocalOnly strategy during this specific simulation run.
    # We will use this as the baseline for all strategies in this iteration.
    total_tasks_generated_for_this_iteration = local_metrics['completed_tasks'] + local_metrics['failed_tasks']

    print(f"Baseline Total tasks generated for this iteration: {total_tasks_generated_for_this_iteration}")
    print(f"Total potential local execution time (LocalOnly baseline): {np.sum(local_metrics['potential_local_latencies']):.4f} seconds")
    # --- End Step 1 ---


    # --- Step 2: Run all strategies, using the established baseline for total_tasks_generated ---
    for name, strategy_class in strategies.items():
        # Skip re-running Local if it's the first in the strategies list and already ran for baseline.
        # However, for consistency and to collect its full metrics, we'll re-run it normally here.
        # If running LocalOnly twice is a performance concern, you can add an 'if name == "Local": ... continue'
        # and use local_metrics directly, but ensuring all strategies follow the same execution path is safer.

        start_time = time.time()
        print(f"\n=== Running {name} Strategy ===")
        # Note: No re-seeding here. The global seed set at the top controls all randomness.
        sim = AutonomousVehicleSimulator(strategy=strategy_class)
        metrics = sim.run(until=SIM_TIME)

        # Ensure these are numpy arrays or lists that can be summed
        metrics['total_potential_local_execution_time'] = np.sum(metrics['potential_local_latencies']) # Keep this calculated for each strategy's metrics

        print(f"Time taken for {name}: {time.time() - start_time:.2f} seconds")
        print(f"Completed tasks: {metrics['completed_tasks']}")
        print(f"Failed tasks: {metrics['failed_tasks']}")
        # IMPORTANT: Print the baseline total tasks generated, not a strategy-specific sum
        print(f"Total tasks generated (baseline for this iteration): {total_tasks_generated_for_this_iteration}")
        print(f"Local processing: {metrics['local_processing']}")
        print(f"V2V processing: {metrics['v2v_processing']}")
        print(f"Offloaded processing: {metrics['offloaded_processing']}")
        print("Offloaded by type:", metrics['offloaded_by_type'])

        avg_latency = np.mean(metrics['task_latencies']) if metrics['task_latencies'] else 0
        total_latency = np.sum(metrics['task_latencies']) if metrics ['task_latencies'] else 0
        total_energy = np.sum(metrics['energy_consumption']) if metrics['energy_consumption'] else 0

        if metrics['task_latencies']:
            print(f"Average task latency: {avg_latency:.4f} seconds")
        else:
            print("No tasks completed to calculate average latency.")

        log_entry = {
            "strategy": name,
            "NUM_VEHICLES": NUM_VEHICLES,
            "SIM_TIME": SIM_TIME,
            "total_tasks_generated": total_tasks_generated_for_this_iteration, # Use the consistent baseline here
            "completed_tasks": metrics['completed_tasks'],
            "failed_tasks": metrics['failed_tasks'],
            "average_latency_seconds": avg_latency,
            "total_energy_joules": total_energy,
            "total_latency_seconds": total_latency,
        }
        run_log_data.append(log_entry)

    return run_log_data


if __name__ == "__main__":
    NUM_RUNS = 10  # Define how many times to run the experiment
    all_runs_data = []

    print(f"\n--- Starting {NUM_RUNS} simulation runs ---")
    for i in range(NUM_RUNS):
        print(f"\n--- Running Experiment Iteration {i + 1}/{NUM_RUNS} ---")
        # Because random.seed and np.random.seed are set once globally,
        # each call to run_single_comparison will continue the same random sequence.
        # This implies that the 'LocalOnly' baseline run will produce the same
        # total_tasks_generated across all outer iterations.
        single_run_results = run_single_comparison()
        for entry in single_run_results:
            entry['run_iteration'] = i + 1  # Add run iteration number
        all_runs_data.extend(single_run_results)

    # Convert the collected data to a pandas DataFrame
    df = pd.DataFrame(all_runs_data)

    # Save to CSV
    csv_file_path = os.path.join(LOG_DIR, f"simulation_results_summary_{int(time.time())}.csv")
    df.to_csv(csv_file_path, index=False)
    print(f"\nAll simulation results aggregated and saved to CSV: {csv_file_path}")
